### ISSUE TITLE
license ?

### ISSUE THREAD

**Issue by timelyportfolio** [stores/d3-linear-mesh#14]
What is the expected license for this great project?  Thanks for the great work.  I would like to potentially wrap for use with [`htmlwidgets`](http://htmlwidgets.org).

**Comment by timelyportfolio** [comment]
Never mind I see it in `bower` .  Would it be ok to pull a License.md ?

**Comment by dandehavilland** [comment]
Thanks for the interest! I've just pushed a license up. 

The lib is alpha at the moment and subject to change, depending on project requirements, but feel free to wrap it up.
